### ISSUE TITLE
Can I use this plugin to load a volumetric 3D texture ?

### ISSUE THREAD

**Issue by Xqua** [SIsilicon/Godot-Volumetrics-Plugin#7]
Hi, I've seen your previous plugin: 
https://github.com/SIsilicon/Volume-Renderer

And in it, you load a 2D texture, tile it, and use multiple slices as a 3D texture. But that was before Texture3D in Godot so that was crafty ! 

Now, I am looking to port a project of mine which allows the visualization of scientific 3D volumetric datasets (mainly microscopy images for now) into Godot. I made it in Unity, but hell Unity is a pain, and I just can't stand the whole .Net universe ! I'd rather write code in C++ and GDscript ! For a quick look at what it did (that was a while ago and I'm trying to revive it)  https://www.youtube.com/watch?v=oS-imSO0qFY

To do that I used a Ray Marching shader in Unity, but I have to admit, I shamelessly reused someone's shader without understanding it. 2 years later, I am trying to learn to write such a shader from scratch in Godot, and well I am banging my head quite a bit ... I can get as far as Signed Distance function, but even then I have trouble setting the Ray Origin ... But I digress !!!

So, is there a way to use this plugin to load a 3D texture ? If so, what format should it be in ? RAW ? PNG slices ? Tiled PNG (that one won't work for me, I mean the datasets I have are a bit massive) 

Thanks a lot !

PS: in your opinion, does Godot have the performances required for a VR volumetric renderer ?

**Comment by SIsilicon** [comment]
The plugin itself is not responsible for loading 3D textures. Godot is. Godot now supports loading 3D textures, which my plugin supports. To import a 3D texture, you'd have to import it in a sort of "flip book" format (Tiled PNG); where each layer of the 3D texture is stored in an atlas left to right, top to bottom (or was it bottom to top?). That's how my plugin generates 3D noise textures as well.
About using this for scientific datasets however, my plugin might not be the best tool for that. It's designed for physically based fog, so it's rendering resolution is low; not a good thing when you're visualizing volumes with great detail. A ray-marcher would be better suited for that task. But if you want to try it anyway, be my guest. Who knows? It might work for your case anyway.

P.S.: This plugin wasn't designed for VR since the performance penalty might be too great.

**Comment by Xqua** [comment]
Thanks for those informations! 

I shall keep on my quest to get my Ray Marcher working then !
